<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('countries')->insert([
            // Africa
            ['code' => 'DZ', 'name' => 'Algeria', 'continent' => 'Africa', 'phone_code' => '+213'],
            ['code' => 'AO', 'name' => 'Angola', 'continent' => 'Africa', 'phone_code' => '+244'],
            ['code' => 'BJ', 'name' => 'Benin', 'continent' => 'Africa', 'phone_code' => '+229'],
            ['code' => 'BW', 'name' => 'Botswana', 'continent' => 'Africa', 'phone_code' => '+267'],
            ['code' => 'BF', 'name' => 'Burkina Faso', 'continent' => 'Africa', 'phone_code' => '+226'],
            ['code' => 'BI', 'name' => 'Burundi', 'continent' => 'Africa', 'phone_code' => '+257'],
            ['code' => 'CM', 'name' => 'Cameroon', 'continent' => 'Africa', 'phone_code' => '+237'],
            ['code' => 'CV', 'name' => 'Cape Verde', 'continent' => 'Africa', 'phone_code' => '+238'],
            ['code' => 'CF', 'name' => 'Central African Republic', 'continent' => 'Africa', 'phone_code' => '+236'],
            ['code' => 'TD', 'name' => 'Chad', 'continent' => 'Africa', 'phone_code' => '+235'],
            ['code' => 'KM', 'name' => 'Comoros', 'continent' => 'Africa', 'phone_code' => '+269'],
            ['code' => 'CG', 'name' => 'Congo - Brazzaville', 'continent' => 'Africa', 'phone_code' => '+242'],
            ['code' => 'CD', 'name' => 'Congo - Kinshasa', 'continent' => 'Africa', 'phone_code' => '+243'],
            ['code' => 'CI', 'name' => 'Côte d\'Ivoire', 'continent' => 'Africa', 'phone_code' => '+225'],
            ['code' => 'DJ', 'name' => 'Djibouti', 'continent' => 'Africa', 'phone_code' => '+253'],
            ['code' => 'EG', 'name' => 'Egypt', 'continent' => 'Africa', 'phone_code' => '+20'],
            ['code' => 'GQ', 'name' => 'Equatorial Guinea', 'continent' => 'Africa', 'phone_code' => '+240'],
            ['code' => 'ER', 'name' => 'Eritrea', 'continent' => 'Africa', 'phone_code' => '+291'],
            ['code' => 'ET', 'name' => 'Ethiopia', 'continent' => 'Africa', 'phone_code' => '+251'],
            ['code' => 'GA', 'name' => 'Gabon', 'continent' => 'Africa', 'phone_code' => '+241'],
            ['code' => 'GM', 'name' => 'Gambia', 'continent' => 'Africa', 'phone_code' => '+220'],
            ['code' => 'GH', 'name' => 'Ghana', 'continent' => 'Africa', 'phone_code' => '+233'],
            ['code' => 'GN', 'name' => 'Guinea', 'continent' => 'Africa', 'phone_code' => '+224'],
            ['code' => 'GW', 'name' => 'Guinea-Bissau', 'continent' => 'Africa', 'phone_code' => '+245'],
            ['code' => 'KE', 'name' => 'Kenya', 'continent' => 'Africa', 'phone_code' => '+254'],
            ['code' => 'LS', 'name' => 'Lesotho', 'continent' => 'Africa', 'phone_code' => '+266'],
            ['code' => 'LR', 'name' => 'Liberia', 'continent' => 'Africa', 'phone_code' => '+231'],
            ['code' => 'LY', 'name' => 'Libya', 'continent' => 'Africa', 'phone_code' => '+218'],
            ['code' => 'MG', 'name' => 'Madagascar', 'continent' => 'Africa', 'phone_code' => '+261'],
            ['code' => 'MW', 'name' => 'Malawi', 'continent' => 'Africa', 'phone_code' => '+265'],
            ['code' => 'ML', 'name' => 'Mali', 'continent' => 'Africa', 'phone_code' => '+223'],
            ['code' => 'MR', 'name' => 'Mauritania', 'continent' => 'Africa', 'phone_code' => '+222'],
            ['code' => 'MU', 'name' => 'Mauritius', 'continent' => 'Africa', 'phone_code' => '+230'],
            ['code' => 'YT', 'name' => 'Mayotte', 'continent' => 'Africa', 'phone_code' => '+262'],
            ['code' => 'MA', 'name' => 'Morocco', 'continent' => 'Africa', 'phone_code' => '+212'],
            ['code' => 'MZ', 'name' => 'Mozambique', 'continent' => 'Africa', 'phone_code' => '+258'],
            ['code' => 'NA', 'name' => 'Namibia', 'continent' => 'Africa', 'phone_code' => '+264'],
            ['code' => 'NE', 'name' => 'Niger', 'continent' => 'Africa', 'phone_code' => '+227'],
            ['code' => 'NG', 'name' => 'Nigeria', 'continent' => 'Africa', 'phone_code' => '+234'],
            ['code' => 'RW', 'name' => 'Rwanda', 'continent' => 'Africa', 'phone_code' => '+250'],
            ['code' => 'RE', 'name' => 'Réunion', 'continent' => 'Africa', 'phone_code' => '+262'],
            ['code' => 'SH', 'name' => 'Saint Helena', 'continent' => 'Africa', 'phone_code' => '+290'],
            ['code' => 'SN', 'name' => 'Senegal', 'continent' => 'Africa', 'phone_code' => '+221'],
            ['code' => 'SC', 'name' => 'Seychelles', 'continent' => 'Africa', 'phone_code' => '+248'],
            ['code' => 'SL', 'name' => 'Sierra Leone', 'continent' => 'Africa', 'phone_code' => '+232'],
            ['code' => 'SO', 'name' => 'Somalia', 'continent' => 'Africa', 'phone_code' => '+252'],
            ['code' => 'ZA', 'name' => 'South Africa', 'continent' => 'Africa', 'phone_code' => '+27'],
            ['code' => 'SD', 'name' => 'Sudan', 'continent' => 'Africa', 'phone_code' => '+249'],
            ['code' => 'SZ', 'name' => 'Eswatini', 'continent' => 'Africa', 'phone_code' => '+268'],
            ['code' => 'ST', 'name' => 'São Tomé and Príncipe', 'continent' => 'Africa', 'phone_code' => '+239'],
            ['code' => 'TZ', 'name' => 'Tanzania', 'continent' => 'Africa', 'phone_code' => '+255'],
            ['code' => 'TG', 'name' => 'Togo', 'continent' => 'Africa', 'phone_code' => '+228'],
            ['code' => 'TN', 'name' => 'Tunisia', 'continent' => 'Africa', 'phone_code' => '+216'],
            ['code' => 'UG', 'name' => 'Uganda', 'continent' => 'Africa', 'phone_code' => '+256'],
            ['code' => 'EH', 'name' => 'Western Sahara', 'continent' => 'Africa', 'phone_code' => '+212'],
            ['code' => 'ZM', 'name' => 'Zambia', 'continent' => 'Africa', 'phone_code' => '+260'],
            ['code' => 'ZW', 'name' => 'Zimbabwe', 'continent' => 'Africa', 'phone_code' => '+263'],

            // Americas
            ['code' => 'AI', 'name' => 'Anguilla', 'continent' => 'Americas', 'phone_code' => '+1-264'],
            ['code' => 'AG', 'name' => 'Antigua and Barbuda', 'continent' => 'Americas', 'phone_code' => '+1-268'],
            ['code' => 'AR', 'name' => 'Argentina', 'continent' => 'Americas', 'phone_code' => '+54'],
            ['code' => 'AW', 'name' => 'Aruba', 'continent' => 'Americas', 'phone_code' => '+297'],
            ['code' => 'BS', 'name' => 'Bahamas', 'continent' => 'Americas', 'phone_code' => '+1-242'],
            ['code' => 'BB', 'name' => 'Barbados', 'continent' => 'Americas', 'phone_code' => '+1-246'],
            ['code' => 'BZ', 'name' => 'Belize', 'continent' => 'Americas', 'phone_code' => '+501'],
            ['code' => 'BM', 'name' => 'Bermuda', 'continent' => 'Americas', 'phone_code' => '+1-441'],
            ['code' => 'BO', 'name' => 'Bolivia', 'continent' => 'Americas', 'phone_code' => '+591'],
            ['code' => 'BR', 'name' => 'Brazil', 'continent' => 'Americas', 'phone_code' => '+55'],
            ['code' => 'VG', 'name' => 'British Virgin Islands', 'continent' => 'Americas', 'phone_code' => '+1-284'],
            ['code' => 'CA', 'name' => 'Canada', 'continent' => 'Americas', 'phone_code' => '+1'],
            ['code' => 'KY', 'name' => 'Cayman Islands', 'continent' => 'Americas', 'phone_code' => '+1-345'],
            ['code' => 'CL', 'name' => 'Chile', 'continent' => 'Americas', 'phone_code' => '+56'],
            ['code' => 'CO', 'name' => 'Colombia', 'continent' => 'Americas', 'phone_code' => '+57'],
            ['code' => 'CR', 'name' => 'Costa Rica', 'continent' => 'Americas', 'phone_code' => '+506'],
            ['code' => 'CU', 'name' => 'Cuba', 'continent' => 'Americas', 'phone_code' => '+53'],
            ['code' => 'DM', 'name' => 'Dominica', 'continent' => 'Americas', 'phone_code' => '+1-767'],
            ['code' => 'DO', 'name' => 'Dominican Republic', 'continent' => 'Americas', 'phone_code' => '+1-809'],
            ['code' => 'EC', 'name' => 'Ecuador', 'continent' => 'Americas', 'phone_code' => '+593'],
            ['code' => 'SV', 'name' => 'El Salvador', 'continent' => 'Americas', 'phone_code' => '+503'],
            ['code' => 'FK', 'name' => 'Falkland Islands', 'continent' => 'Americas', 'phone_code' => '+500'],
            ['code' => 'GF', 'name' => 'French Guiana', 'continent' => 'Americas', 'phone_code' => '+594'],
            ['code' => 'GL', 'name' => 'Greenland', 'continent' => 'Americas', 'phone_code' => '+299'],
            ['code' => 'GD', 'name' => 'Grenada', 'continent' => 'Americas', 'phone_code' => '+1-473'],
            ['code' => 'GP', 'name' => 'Guadeloupe', 'continent' => 'Americas', 'phone_code' => '+590'],
            ['code' => 'GT', 'name' => 'Guatemala', 'continent' => 'Americas', 'phone_code' => '+502'],
            ['code' => 'GY', 'name' => 'Guyana', 'continent' => 'Americas', 'phone_code' => '+592'],
            ['code' => 'HT', 'name' => 'Haiti', 'continent' => 'Americas', 'phone_code' => '+509'],
            ['code' => 'HN', 'name' => 'Honduras', 'continent' => 'Americas', 'phone_code' => '+504'],
            ['code' => 'JM', 'name' => 'Jamaica', 'continent' => 'Americas', 'phone_code' => '+1-876'],
            ['code' => 'MQ', 'name' => 'Martinique', 'continent' => 'Americas', 'phone_code' => '+596'],
            ['code' => 'MX', 'name' => 'Mexico', 'continent' => 'Americas', 'phone_code' => '+52'],
            ['code' => 'MS', 'name' => 'Montserrat', 'continent' => 'Americas', 'phone_code' => '+1-664'],
            ['code' => 'NI', 'name' => 'Nicaragua', 'continent' => 'Americas', 'phone_code' => '+505'],
            ['code' => 'PA', 'name' => 'Panama', 'continent' => 'Americas', 'phone_code' => '+507'],
            ['code' => 'PY', 'name' => 'Paraguay', 'continent' => 'Americas', 'phone_code' => '+595'],
            ['code' => 'PE', 'name' => 'Peru', 'continent' => 'Americas', 'phone_code' => '+51'],
            ['code' => 'PR', 'name' => 'Puerto Rico', 'continent' => 'Americas', 'phone_code' => '+1-787'],
            ['code' => 'BL', 'name' => 'Saint Barthélemy', 'continent' => 'Americas', 'phone_code' => '+590'],
            ['code' => 'KN', 'name' => 'Saint Kitts and Nevis', 'continent' => 'Americas', 'phone_code' => '+1-869'],
            ['code' => 'LC', 'name' => 'Saint Lucia', 'continent' => 'Americas', 'phone_code' => '+1-758'],
            ['code' => 'MF', 'name' => 'Saint Martin', 'continent' => 'Americas', 'phone_code' => '+590'],
            ['code' => 'PM', 'name' => 'Saint Pierre and Miquelon', 'continent' => 'Americas', 'phone_code' => '+508'],
            ['code' => 'VC', 'name' => 'Saint Vincent and the Grenadines', 'continent' => 'Americas', 'phone_code' => '+1-784'],
            ['code' => 'SR', 'name' => 'Suriname', 'continent' => 'Americas', 'phone_code' => '+597'],
            ['code' => 'TT', 'name' => 'Trinidad and Tobago', 'continent' => 'Americas', 'phone_code' => '+1-868'],
            ['code' => 'TC', 'name' => 'Turks and Caicos Islands', 'continent' => 'Americas', 'phone_code' => '+1-649'],
            ['code' => 'VI', 'name' => 'U.S. Virgin Islands', 'continent' => 'Americas', 'phone_code' => '+1-340'],
            ['code' => 'US', 'name' => 'United States', 'continent' => 'Americas', 'phone_code' => '+1'],
            ['code' => 'UY', 'name' => 'Uruguay', 'continent' => 'Americas', 'phone_code' => '+598'],
            ['code' => 'VE', 'name' => 'Venezuela', 'continent' => 'Americas', 'phone_code' => '+58'],

            // Asia
            ['code' => 'AF', 'name' => 'Afghanistan', 'continent' => 'Asia', 'phone_code' => '+93'],
            ['code' => 'AM', 'name' => 'Armenia', 'continent' => 'Asia', 'phone_code' => '+374'],
            ['code' => 'AZ', 'name' => 'Azerbaijan', 'continent' => 'Asia', 'phone_code' => '+994'],
            ['code' => 'BH', 'name' => 'Bahrain', 'continent' => 'Asia', 'phone_code' => '+973'],
            ['code' => 'BD', 'name' => 'Bangladesh', 'continent' => 'Asia', 'phone_code' => '+880'],
            ['code' => 'BT', 'name' => 'Bhutan', 'continent' => 'Asia', 'phone_code' => '+975'],
            ['code' => 'BN', 'name' => 'Brunei', 'continent' => 'Asia', 'phone_code' => '+673'],
            ['code' => 'KH', 'name' => 'Cambodia', 'continent' => 'Asia', 'phone_code' => '+855'],
            ['code' => 'CN', 'name' => 'China', 'continent' => 'Asia', 'phone_code' => '+86'],
            ['code' => 'GE', 'name' => 'Georgia', 'continent' => 'Asia', 'phone_code' => '+995'],
            ['code' => 'HK', 'name' => 'Hong Kong SAR China', 'continent' => 'Asia', 'phone_code' => '+852'],
            ['code' => 'IN', 'name' => 'India', 'continent' => 'Asia', 'phone_code' => '+91'],
            ['code' => 'ID', 'name' => 'Indonesia', 'continent' => 'Asia', 'phone_code' => '+62'],
            ['code' => 'IR', 'name' => 'Iran', 'continent' => 'Asia', 'phone_code' => '+98'],
            ['code' => 'IQ', 'name' => 'Iraq', 'continent' => 'Asia', 'phone_code' => '+964'],
            ['code' => 'IL', 'name' => 'Israel', 'continent' => 'Asia', 'phone_code' => '+972'],
            ['code' => 'JP', 'name' => 'Japan', 'continent' => 'Asia', 'phone_code' => '+81'],
            ['code' => 'JO', 'name' => 'Jordan', 'continent' => 'Asia', 'phone_code' => '+962'],
            ['code' => 'KZ', 'name' => 'Kazakhstan', 'continent' => 'Asia', 'phone_code' => '+7'],
            ['code' => 'KW', 'name' => 'Kuwait', 'continent' => 'Asia', 'phone_code' => '+965'],
            ['code' => 'KG', 'name' => 'Kyrgyzstan', 'continent' => 'Asia', 'phone_code' => '+996'],
            ['code' => 'LA', 'name' => 'Laos', 'continent' => 'Asia', 'phone_code' => '+856'],
            ['code' => 'LB', 'name' => 'Lebanon', 'continent' => 'Asia', 'phone_code' => '+961'],
            ['code' => 'MO', 'name' => 'Macau SAR China', 'continent' => 'Asia', 'phone_code' => '+853'],
            ['code' => 'MY', 'name' => 'Malaysia', 'continent' => 'Asia', 'phone_code' => '+60'],
            ['code' => 'MV', 'name' => 'Maldives', 'continent' => 'Asia', 'phone_code' => '+960'],
            ['code' => 'MN', 'name' => 'Mongolia', 'continent' => 'Asia', 'phone_code' => '+976'],
            ['code' => 'MM', 'name' => 'Myanmar (Burma)', 'continent' => 'Asia', 'phone_code' => '+95'],
            ['code' => 'NP', 'name' => 'Nepal', 'continent' => 'Asia', 'phone_code' => '+977'],
            ['code' => 'KP', 'name' => 'North Korea', 'continent' => 'Asia', 'phone_code' => '+850'],
            ['code' => 'OM', 'name' => 'Oman', 'continent' => 'Asia', 'phone_code' => '+968'],
            ['code' => 'PK', 'name' => 'Pakistan', 'continent' => 'Asia', 'phone_code' => '+92'],
            ['code' => 'PS', 'name' => 'Palestinian Territories', 'continent' => 'Asia', 'phone_code' => '+970'],
            ['code' => 'PH', 'name' => 'Philippines', 'continent' => 'Asia', 'phone_code' => '+63'],
            ['code' => 'QA', 'name' => 'Qatar', 'continent' => 'Asia', 'phone_code' => '+974'],
            ['code' => 'SA', 'name' => 'Saudi Arabia', 'continent' => 'Asia', 'phone_code' => '+966'],
            ['code' => 'SG', 'name' => 'Singapore', 'continent' => 'Asia', 'phone_code' => '+65'],
            ['code' => 'KR', 'name' => 'South Korea', 'continent' => 'Asia', 'phone_code' => '+82'],
            ['code' => 'LK', 'name' => 'Sri Lanka', 'continent' => 'Asia', 'phone_code' => '+94'],
            ['code' => 'SY', 'name' => 'Syria', 'continent' => 'Asia', 'phone_code' => '+963'],
            ['code' => 'TW', 'name' => 'Taiwan', 'continent' => 'Asia', 'phone_code' => '+886'],
            ['code' => 'TJ', 'name' => 'Tajikistan', 'continent' => 'Asia', 'phone_code' => '+992'],
            ['code' => 'TH', 'name' => 'Thailand', 'continent' => 'Asia', 'phone_code' => '+66'],
            ['code' => 'TL', 'name' => 'Timor-Leste', 'continent' => 'Asia', 'phone_code' => '+670'],
            ['code' => 'TR', 'name' => 'Turkey', 'continent' => 'Asia', 'phone_code' => '+90'],
            ['code' => 'TM', 'name' => 'Turkmenistan', 'continent' => 'Asia', 'phone_code' => '+993'],
            ['code' => 'AE', 'name' => 'United Arab Emirates', 'continent' => 'Asia', 'phone_code' => '+971'],
            ['code' => 'UZ', 'name' => 'Uzbekistan', 'continent' => 'Asia', 'phone_code' => '+998'],
            ['code' => 'VN', 'name' => 'Vietnam', 'continent' => 'Asia', 'phone_code' => '+84'],
            ['code' => 'YE', 'name' => 'Yemen', 'continent' => 'Asia', 'phone_code' => '+967'],

            // Europe
            ['code' => 'AL', 'name' => 'Albania', 'continent' => 'Europe', 'phone_code' => '+355'],
            ['code' => 'AD', 'name' => 'Andorra', 'continent' => 'Europe', 'phone_code' => '+376'],
            ['code' => 'AT', 'name' => 'Austria', 'continent' => 'Europe', 'phone_code' => '+43'],
            ['code' => 'BY', 'name' => 'Belarus', 'continent' => 'Europe', 'phone_code' => '+375'],
            ['code' => 'BE', 'name' => 'Belgium', 'continent' => 'Europe', 'phone_code' => '+32'],
            ['code' => 'BA', 'name' => 'Bosnia and Herzegovina', 'continent' => 'Europe', 'phone_code' => '+387'],
            ['code' => 'BG', 'name' => 'Bulgaria', 'continent' => 'Europe', 'phone_code' => '+359'],
            ['code' => 'HR', 'name' => 'Croatia', 'continent' => 'Europe', 'phone_code' => '+385'],
            ['code' => 'CY', 'name' => 'Cyprus', 'continent' => 'Europe', 'phone_code' => '+357'],
            ['code' => 'CZ', 'name' => 'Czech Republic', 'continent' => 'Europe', 'phone_code' => '+420'],
            ['code' => 'DK', 'name' => 'Denmark', 'continent' => 'Europe', 'phone_code' => '+45'],
            ['code' => 'EE', 'name' => 'Estonia', 'continent' => 'Europe', 'phone_code' => '+372'],
            ['code' => 'FI', 'name' => 'Finland', 'continent' => 'Europe', 'phone_code' => '+358'],
            ['code' => 'FR', 'name' => 'France', 'continent' => 'Europe', 'phone_code' => '+33'],
            ['code' => 'DE', 'name' => 'Germany', 'continent' => 'Europe', 'phone_code' => '+49'],
            ['code' => 'GR', 'name' => 'Greece', 'continent' => 'Europe', 'phone_code' => '+30'],
            ['code' => 'HU', 'name' => 'Hungary', 'continent' => 'Europe', 'phone_code' => '+36'],
            ['code' => 'IS', 'name' => 'Iceland', 'continent' => 'Europe', 'phone_code' => '+354'],
            ['code' => 'IE', 'name' => 'Ireland', 'continent' => 'Europe', 'phone_code' => '+353'],
            ['code' => 'IT', 'name' => 'Italy', 'continent' => 'Europe', 'phone_code' => '+39'],
            ['code' => 'XK', 'name' => 'Kosovo', 'continent' => 'Europe', 'phone_code' => '+383'],
            ['code' => 'LV', 'name' => 'Latvia', 'continent' => 'Europe', 'phone_code' => '+371'],
            ['code' => 'LI', 'name' => 'Liechtenstein', 'continent' => 'Europe', 'phone_code' => '+423'],
            ['code' => 'LT', 'name' => 'Lithuania', 'continent' => 'Europe', 'phone_code' => '+370'],
            ['code' => 'LU', 'name' => 'Luxembourg', 'continent' => 'Europe', 'phone_code' => '+352'],
            ['code' => 'MT', 'name' => 'Malta', 'continent' => 'Europe', 'phone_code' => '+356'],
            ['code' => 'MD', 'name' => 'Moldova', 'continent' => 'Europe', 'phone_code' => '+373'],
            ['code' => 'MC', 'name' => 'Monaco', 'continent' => 'Europe', 'phone_code' => '+377'],
            ['code' => 'ME', 'name' => 'Montenegro', 'continent' => 'Europe', 'phone_code' => '+382'],
            ['code' => 'NL', 'name' => 'Netherlands', 'continent' => 'Europe', 'phone_code' => '+31'],
            ['code' => 'MK', 'name' => 'North Macedonia', 'continent' => 'Europe', 'phone_code' => '+389'],
            ['code' => 'NO', 'name' => 'Norway', 'continent' => 'Europe', 'phone_code' => '+47'],
            ['code' => 'PL', 'name' => 'Poland', 'continent' => 'Europe', 'phone_code' => '+48'],
            ['code' => 'PT', 'name' => 'Portugal', 'continent' => 'Europe', 'phone_code' => '+351'],
            ['code' => 'RO', 'name' => 'Romania', 'continent' => 'Europe', 'phone_code' => '+40'],
            ['code' => 'RU', 'name' => 'Russia', 'continent' => 'Europe', 'phone_code' => '+7'],
            ['code' => 'SM', 'name' => 'San Marino', 'continent' => 'Europe', 'phone_code' => '+378'],
            ['code' => 'RS', 'name' => 'Serbia', 'continent' => 'Europe', 'phone_code' => '+381'],
            ['code' => 'SK', 'name' => 'Slovakia', 'continent' => 'Europe', 'phone_code' => '+421'],
            ['code' => 'SI', 'name' => 'Slovenia', 'continent' => 'Europe', 'phone_code' => '+386'],
            ['code' => 'ES', 'name' => 'Spain', 'continent' => 'Europe', 'phone_code' => '+34'],
            ['code' => 'SE', 'name' => 'Sweden', 'continent' => 'Europe', 'phone_code' => '+46'],
            ['code' => 'CH', 'name' => 'Switzerland', 'continent' => 'Europe', 'phone_code' => '+41'],
            ['code' => 'UA', 'name' => 'Ukraine', 'continent' => 'Europe', 'phone_code' => '+380'],
            ['code' => 'GB', 'name' => 'United Kingdom', 'continent' => 'Europe', 'phone_code' => '+44'],
            ['code' => 'VA', 'name' => 'Vatican City', 'continent' => 'Europe', 'phone_code' => '+379'],
        ]);
    }
}
